import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "./Context/UserContext";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
// or `v1X-appRouter` if you are using Next.js v1X
import ButtonAppBar from "./components/AppBar.jsx";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <UserProvider>
            <ButtonAppBar />
            {props.children}
          </UserProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
